//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOQ_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOQ_Items()
        {
            this.C_Cost_Project_Codes_Items = new HashSet<C_Cost_Project_Codes_Items>();
            this.BOQ_Items1 = new HashSet<BOQ_Items>();
            this.Item_Breakdowns = new HashSet<Item_Breakdowns>();
        }
    
        public int Id { get; set; }
        public int BOQId { get; set; }
        public Nullable<int> Unit { get; set; }
        public decimal Quantity { get; set; }
        public string BOQRef { get; set; }
        public decimal PlanedUnitPrice { get; set; }
        public Nullable<int> ParentId { get; set; }
        public short HierarcyType { get; set; }
        public string Description { get; set; }
        public decimal PlanedUnitPriceWithoutProfit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Cost_Project_Codes_Items> C_Cost_Project_Codes_Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOQ_Items> BOQ_Items1 { get; set; }
        public virtual BOQ_Items BOQ_Items2 { get; set; }
        public virtual BOQ BOQ { get; set; }
        public virtual Unit Unit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Item_Breakdowns> Item_Breakdowns { get; set; }
    }
}
