//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cost_Indirect_Project_Code_Summerizing
    {
        public int Projcet_Code_Id { get; set; }
        public int Indirect_Cost_Item_Id { get; set; }
        public decimal Planned_Price { get; set; }
        public decimal Ref_Price { get; set; }
    
        public virtual IndirectCostItem IndirectCostItem { get; set; }
        public virtual C_Cost_Project_Codes C_Cost_Project_Codes { get; set; }
    }
}
