//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Breakdowns
    {
        public int Id { get; set; }
        public decimal TotalPrice { get; set; }
        public int BOQ_Items_Id { get; set; }
        public short TypeId { get; set; }
    
        public virtual BOQ_Items BOQ_Items { get; set; }
        public virtual BreakdownItemType BreakdownItemType { get; set; }
    }
}
