//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Cost_Project_Codes
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<int> Unified_Code { get; set; }
        public string NameCategories { get; set; }
        public string Node { get; set; }
        public Nullable<short> GetLevelNode { get; set; }
        public string NameProjects { get; set; }
    }
}
