//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOQs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOQs()
        {
            this.BOQ_Items = new HashSet<BOQ_Items>();
            this.IndirectCostItems = new HashSet<IndirectCostItems>();
        }
    
        public int Id { get; set; }
        public short Rev { get; set; }
        public System.DateTime RevDate { get; set; }
        public Nullable<int> ContractId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOQ_Items> BOQ_Items { get; set; }
        public virtual Projects Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IndirectCostItems> IndirectCostItems { get; set; }
    }
}
