//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cost_Direct_Project_Codes_Summerizng
    {
        public int Project_Code_Id { get; set; }
        public int Boq_Item_Id { get; set; }
        public short Break_Down_Type_Id { get; set; }
        public decimal Planned_Price { get; set; }
        public decimal Ref_Price { get; set; }
    
        public virtual BreakdownItemType BreakdownItemType { get; set; }
        public virtual C_Cost_Project_Codes_Items C_Cost_Project_Codes_Items { get; set; }
    }
}
