//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Models
{
    using PSC_Cost_Control.Helper.Interfaces;
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cost_Unified_Codes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public C_Cost_Unified_Codes()
        {
            this.C_Cost_Project_Codes = new HashSet<C_Cost_Project_Codes>();
            this.C_Cost_Unified_Codes1 = new HashSet<C_Cost_Unified_Codes>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> Category_Id { get; set; }
        public Nullable<int> Parent { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Cost_Project_Codes> C_Cost_Project_Codes { get; set; }
        public virtual C_Cost_Unified_Code_Category C_Cost_Unified_Code_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_Cost_Unified_Codes> C_Cost_Unified_Codes1 { get; set; }
        public virtual C_Cost_Unified_Codes C_Cost_Unified_Codes2 { get; set; }

    }
}
