//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSC_Cost_Control.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PSC_COST3Entities : DbContext
    {
        public PSC_COST3Entities()
            : base("name=PSC_COST3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Cost_Direct_Project_Codes_Summerizng> C_Cost_Direct_Project_Codes_Summerizng { get; set; }
        public virtual DbSet<C_Cost_Indirect_Project_Code_Summerizing> C_Cost_Indirect_Project_Code_Summerizing { get; set; }
        public virtual DbSet<C_Cost_Project_Code_Categories> C_Cost_Project_Code_Categories { get; set; }
        public virtual DbSet<C_Cost_Project_Codes> C_Cost_Project_Codes { get; set; }
        public virtual DbSet<C_Cost_Project_Codes_Items> C_Cost_Project_Codes_Items { get; set; }
        public virtual DbSet<C_Cost_Unified_Code_Category> C_Cost_Unified_Code_Category { get; set; }
        public virtual DbSet<C_Cost_Unified_Codes> C_Cost_Unified_Codes { get; set; }
        public virtual DbSet<BOQ_Items> BOQ_Items { get; set; }
        public virtual DbSet<BOQs> BOQs { get; set; }
        public virtual DbSet<BreakdownItemType> BreakdownItemType { get; set; }
        public virtual DbSet<IndirectCostItems> IndirectCostItems { get; set; }
        public virtual DbSet<Item_Breakdowns> Item_Breakdowns { get; set; }
        public virtual DbSet<Projects> Projects { get; set; }
        public virtual DbSet<Units> Units { get; set; }
    
        public virtual int f_Cost_SP_Insert_Project_Codes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_Cost_SP_Insert_Project_Codes");
        }
    
        public virtual int f_Cost_SP_Insert_Unified_Codes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("f_Cost_SP_Insert_Unified_Codes");
        }
    }
}
