using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using PSC_Cost_Control.Model;
using PSC_Cost_Control.Helper;
using System.Data.Entity;
using DevExpress.XtraBars.Docking2010;

namespace PSC_Cost_Control.Forms.Project_Code
{
    public partial class Frm_ProjectCode_Show : DevExpress.XtraEditors.XtraForm
    {
        readonly Static st = new Static();

        private readonly PSC_COST2Entities context = new PSC_COST2Entities();

        public List<C_Cost_Project_Codes> _Cost_Project_Codes = new List<C_Cost_Project_Codes>();
        public List<C_Cost_Project_Code_Categories> _Categories = new List<C_Cost_Project_Code_Categories>();
        public List<Project> _Projects = new List<Project>();
        public List<View_Cost_Project_Codes> _View_Cost_Project_Codes = new List<View_Cost_Project_Codes>();

        public List<BOQ_Items> _Boq_Items = new List<BOQ_Items>();
        public List<IndirectCostItem> _IndirectCostItems = new List<IndirectCostItem>();
        


        public Frm_ProjectCode_Show()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            PSC_Cost_Control.Model.PSC_COST2Entities dbContext = new PSC_Cost_Control.Model.PSC_COST2Entities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.View_Cost_Project_Codes.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                treeList1.DataSource = dbContext.View_Cost_Project_Codes.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
        void NewUI()
        {
            var resultProjects = _Projects.ToList();
            if (resultProjects.Count > 0 && resultProjects != null)
            {

                slk_Project.Properties.DataSource = resultProjects;
                slk_Project.Properties.ValueMember = "ContractId";
                slk_Project.Properties.DisplayMember = "Name";
                slk_Project.EditValue = resultProjects[0].ContractId;


            }
            slk_BOQItems.SelectedText = "";
            slk_IndirectCostItems.SelectedText = "";
            //var resultBoq = _Boq_Items.Where(x=> x.BOQId = .ToList();
            //if (resultBoq.Count > 0 && resultBoq != null)
            //{

            //    slk_BOQItems.Properties.DataSource = resultBoq;
            //    slk_BOQItems.Properties.ValueMember = "Id";
            //    slk_BOQItems.Properties.DisplayMember = "Description";
            //    slk_BOQItems.EditValue = resultBoq[0].Id;


            //}
        }

        private void windowsUIButtonPanel1_Click(object sender, EventArgs e)
        {

        }

        private void windowsUIButtonPanel1_ButtonClick(object sender, ButtonEventArgs e)
        {
            WindowsUIButton btn = e.Button as WindowsUIButton;
            if (btn.Caption == "جديد")
            {
                
            }
        }

        private void slk_Project_EditValueChanged(object sender, EventArgs e)
        {
            var ValueProject = Convert.ToInt32(slk_Project.EditValue.ToString());
            if(ValueProject > 0)
            {

            }
        }
    }
}